// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCllvfqJYPi-tTDM6yfmhZzrFdb8IbZb7E',
    appId: '1:1044862267047:web:3e619a1d19bec2a33b7582',
    messagingSenderId: '1044862267047',
    projectId: 'walaa-29e31',
    authDomain: 'walaa-29e31.firebaseapp.com',
    storageBucket: 'walaa-29e31.appspot.com',
    measurementId: 'G-R9F8R65LNF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAugRQj4O4XkMtu3v8ENpDj2s_wQ3--_lc',
    appId: '1:1044862267047:android:48e7173bf168987e3b7582',
    messagingSenderId: '1044862267047',
    projectId: 'walaa-29e31',
    storageBucket: 'walaa-29e31.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBk3mBVxAl4LzBANjyvtuicnHZsI1vEr4g',
    appId: '1:1044862267047:ios:c92a79ea28ac38cd3b7582',
    messagingSenderId: '1044862267047',
    projectId: 'walaa-29e31',
    storageBucket: 'walaa-29e31.appspot.com',
    androidClientId: '1044862267047-eta6rtm1gisgcp78l8nenjg1e7f4ngah.apps.googleusercontent.com',
    iosClientId: '1044862267047-76lsiitashf01lj7bvpublhbjef0rqdf.apps.googleusercontent.com',
    iosBundleId: 'com.topbusiness.walaaprovider',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBk3mBVxAl4LzBANjyvtuicnHZsI1vEr4g',
    appId: '1:1044862267047:ios:c92a79ea28ac38cd3b7582',
    messagingSenderId: '1044862267047',
    projectId: 'walaa-29e31',
    storageBucket: 'walaa-29e31.appspot.com',
    androidClientId: '1044862267047-eta6rtm1gisgcp78l8nenjg1e7f4ngah.apps.googleusercontent.com',
    iosClientId: '1044862267047-76lsiitashf01lj7bvpublhbjef0rqdf.apps.googleusercontent.com',
    iosBundleId: 'com.topbusiness.walaaprovider',
  );
}
